---
ID: "9c921367-b921-4d9b-bbfa-944253caab82"
Parent: "25269b92-cc44-46a9-8c77-da099bf8992c"
Template: "25269b92-cc44-46a9-8c77-da099bf8992c"
Path: /sitecore/templates/Foundation/Commerce/_CatalogContext/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180109T192722Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
